## Numpy array and basics
learn about numpy with chai aur code

In [4]:
import numpy as np

In [2]:
## creating array from list

In [4]:
arr_1d = np.array([1,2,3,4,5])
print("id array:",arr_1d)

arr_2d =np.array([[1,2,3],[4,5,6]])
print("2d array:",arr_2d)


id array: [1 2 3 4 5]
2d array: [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [10]:
py_list = [1,2,3]
print("python list multiplication",py_list*2)

np_array = np.array([1,2,3]) #element wise multipllication
print("python array multiplication",np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n list operation time:", time.time()-start)

start = time.time()
np_array = np.arange(1000000) *2
print("\n numpy operation time:", time.time()-start)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]

 list operation time: 0.10957622528076172

 numpy operation time: 0.006600618362426758


In [11]:
### creating array from scratch


In [18]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

ones= np.ones((2,3))
print("one array:\n",ones)

full = np.full((2,2),7)
print("full array:\n",full)

random = np.random.random((2,3))
print("random array:\n",random)

sequence = np.arange(0,11,2)
print("sequence array:\n",sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7]
 [7 7]]
random array:
 [[0.12794004 0.59518573 0.23674822]
 [0.34171758 0.04682722 0.75114426]]
sequence array:
 [ 0  2  4  6  8 10]


In [19]:
## vector ,matrix and tensor

In [25]:
vector = np.array([1,2,3])
print("vector:",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix:",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor:",tensor)


vector: [1 2 3]
matrix: [[1 2 3]
 [4 5 6]]
tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
### array properties

In [34]:
arr = np.array([[1,2,3],[4,5,"5.5"]])
print("shape",arr.shape)
print("dimension",arr.ndim)
print("size",arr.size)
print("dtype",arr.dtype)

shape (2, 3)
dimension 2
size 6
dtype <U21


In [35]:
### array reshaping

In [40]:
arr = np.arange(12)
print("original array", arr)

reshaped = arr.reshape((3,4))
print("reshaped array", reshaped)

flattend = reshaped.flatten()
print("flattend array", flattend)

#ravel (returns view , insted of copy)
raveled = reshaped.ravel()
print("\n raveled array", raveled)

# transpose 
transpose = reshaped.T
print("\n transposed array", transpose)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattend array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
