## numpy array operation

In [3]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic sclicing", arr[2:7])
print("with step", arr[1:8:2])
print("negative indexing", arr[-3])

basic sclicing [3 4 5 6 7]
with step [2 4 6 8]
negative indexing 8


In [5]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element", arr_2d[1,2])
print("entire row: ", arr_2d[1])
print("entire row: ", arr_2d[:,1])

specific element 6
entire row:  [4 5 6]
entire row:  [2 5 8]


In [13]:
## Sorting

In [13]:
unsorted = np.array([3,1,4,5,3,6,8,3,2,4])
print("sorted array", np.sort(unsorted))


arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by column", np.sort(arr_2d_unsorted,axis=0))

sorted array [1 2 3 3 3 4 4 5 6 8]
sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]


In [2]:
## Filter

In [5]:
numbers = np.array([1,2,3,4,5,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers", even_number)

Even Numbers [ 2  4  6  8 10]


In [11]:
## Filter With Mask

In [12]:
mask = numbers > 5
print("numbers greater than 5", numbers[mask])

numbers greater than 5 [ 6  7  8  9 10]


In [15]:
## fancy indexing vs np.where()

In [11]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print(where_result)
print("np where", numbers[where_result])

[1 3 5]
(array([ 6,  7,  8,  9, 10]),)
np where [ 6  7  8  9 10]


In [7]:
condition_array = np.where(numbers>5, "True", "false")
print(condition_array)


['false' 'false' 'false' 'false' 'false' 'false' 'True' 'True' 'True'
 'True' 'True']


In [15]:
## adding and removing data

In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
add = arr1+arr2
print(add)
combined =np.concatenate((arr1,arr2))
print(combined)

[5 7 9]
[1 2 3 4 5 6]


In [18]:
## array compatibility

In [5]:
a = np.array([1,2,3])
b= np.array([4,5,6])
c=np.array([7,8,9])
print("compatibilty shapes ",a.shape==b.shape)

compatibilty shapes  True


In [8]:
original= np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print("with new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new column [[1 2 7]
 [3 4 8]]


In [9]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print("array after deletion:",deleted)

array after deletion: [1 2 4 5]
